# AUTOMATICALLY GENERATED by https://github.com/tqdm/shtab
# Usage:
# 1) Copy this to somewhere (e.g. ~/.local/share/bash_completion/sane).
# 2) Add the following line to your .bashrc:
#    source ~/.local/share/bash_completion/sane
# See also: https://github.com/scop/bash-completion/blob/main/doc/configuration.md

_shtab_sane_view_subparsers=(usage status state logs summary)
_shtab_sane_subparsers=(workflow view)

_shtab_sane_workflow_option_strings=(-h --help -p --path -w --working_dir -s --search_pattern -a --actions -f --filter -r --run -l --list -d --dry-run -sh --specific_host -sl --save_location -ll --log_location -v --verbose -g --debug_level -vg --view_graph -fl --force_local -m --mode -n --new --patch -vr --virtual_relaunch -ml --main_log -vh --virtual_host)
_shtab_sane_view_usage_option_strings=(-h --help -f --filename -a --arrows -s --stems)
_shtab_sane_view_status_option_strings=(-h --help -f --filename -l --line_length)
_shtab_sane_view_state_option_strings=(-h --help -f --filename -l --line_length)
_shtab_sane_view_logs_option_strings=(-h --help -f --filename -e --errors -r --runlog -rp --relative_path -md --markdown)
_shtab_sane_view_summary_option_strings=(-h --help -f --filename -md --markdown)
_shtab_sane_view_option_strings=(-h --help)
_shtab_sane_option_strings=(-h --help)



_shtab_sane_view_pos_0_choices=(usage status state logs summary)
_shtab_sane_pos_0_choices=(workflow view)

_shtab_sane_workflow__h_nargs=0
_shtab_sane_workflow___help_nargs=0
_shtab_sane_workflow__a_nargs=+
_shtab_sane_workflow___actions_nargs=+
_shtab_sane_workflow__r_nargs=0
_shtab_sane_workflow___run_nargs=0
_shtab_sane_workflow__l_nargs=0
_shtab_sane_workflow___list_nargs=0
_shtab_sane_workflow__d_nargs=0
_shtab_sane_workflow___dry_run_nargs=0
_shtab_sane_workflow__v_nargs=0
_shtab_sane_workflow___verbose_nargs=0
_shtab_sane_workflow__g_nargs='?'
_shtab_sane_workflow___debug_level_nargs='?'
_shtab_sane_workflow__vg_nargs=0
_shtab_sane_workflow___view_graph_nargs=0
_shtab_sane_workflow__fl_nargs=0
_shtab_sane_workflow___force_local_nargs=0
_shtab_sane_workflow__n_nargs=0
_shtab_sane_workflow___new_nargs=0
_shtab_sane_view_usage__h_nargs=0
_shtab_sane_view_usage___help_nargs=0
_shtab_sane_view_usage__a_nargs=0
_shtab_sane_view_usage___arrows_nargs=0
_shtab_sane_view_usage__s_nargs=0
_shtab_sane_view_usage___stems_nargs=0
_shtab_sane_view_status__h_nargs=0
_shtab_sane_view_status___help_nargs=0
_shtab_sane_view_state__h_nargs=0
_shtab_sane_view_state___help_nargs=0
_shtab_sane_view_logs__h_nargs=0
_shtab_sane_view_logs___help_nargs=0
_shtab_sane_view_logs__e_nargs=0
_shtab_sane_view_logs___errors_nargs=0
_shtab_sane_view_logs__r_nargs=0
_shtab_sane_view_logs___runlog_nargs=0
_shtab_sane_view_logs__rp_nargs=0
_shtab_sane_view_logs___relative_path_nargs=0
_shtab_sane_view_logs__md_nargs=0
_shtab_sane_view_logs___markdown_nargs=0
_shtab_sane_view_summary__h_nargs=0
_shtab_sane_view_summary___help_nargs=0
_shtab_sane_view_summary__md_nargs=0
_shtab_sane_view_summary___markdown_nargs=0
_shtab_sane_view_pos_0_nargs=A...
_shtab_sane_view__h_nargs=0
_shtab_sane_view___help_nargs=0
_shtab_sane_pos_0_nargs=A...
_shtab_sane__h_nargs=0
_shtab_sane___help_nargs=0


# $1=COMP_WORDS[1]
_shtab_compgen_files() {
  compgen -f -- $1  # files
}

# $1=COMP_WORDS[1]
_shtab_compgen_dirs() {
  compgen -d -- $1  # recurse into subdirs
}

# $1=COMP_WORDS[1]
_shtab_replace_nonword() {
  echo "${1//[^[:word:]]/_}"
}

# set default values (called for the initial parser & any subparsers)
_set_parser_defaults() {
  local subparsers_var="${prefix}_subparsers[@]"
  sub_parsers=${!subparsers_var-}

  local current_option_strings_var="${prefix}_option_strings[@]"
  current_option_strings=${!current_option_strings_var}

  completed_positional_actions=0

  _set_new_action "pos_$completed_positional_actions" true
}

# $1=action identifier
# $2=positional action (bool)
# set all identifiers for an action's parameters
_set_new_action() {
  current_action="${prefix}_$(_shtab_replace_nonword $1)"

  local current_action_compgen_var=${current_action}_COMPGEN
  current_action_compgen="${!current_action_compgen_var-}"

  local current_action_choices_var="${current_action}_choices[@]"
  current_action_choices="${!current_action_choices_var-}"

  local current_action_nargs_var="${current_action}_nargs"
  if [ -n "${!current_action_nargs_var-}" ]; then
    current_action_nargs="${!current_action_nargs_var}"
  else
    current_action_nargs=1
  fi

  current_action_args_start_index=$(( $word_index + 1 - $pos_only ))

  current_action_is_positional=$2
}

# Notes:
# `COMPREPLY`: what will be rendered after completion is triggered
# `completing_word`: currently typed word to generate completions for
# `${!var}`: evaluates the content of `var` and expand its content as a variable
#     hello="world"
#     x="hello"
#     ${!x} -> ${hello} -> "world"
_shtab_sane() {
  local completing_word="${COMP_WORDS[COMP_CWORD]}"
  local previous_word="${COMP_WORDS[COMP_CWORD-1]}"
  local completed_positional_actions
  local current_action
  local current_action_args_start_index
  local current_action_choices
  local current_action_compgen
  local current_action_is_positional
  local current_action_nargs
  local current_option_strings
  local sub_parsers
  COMPREPLY=()

  local prefix=_shtab_sane
  local word_index=0
  local pos_only=0 # "--" delimiter not encountered yet
  _set_parser_defaults
  word_index=1

  # determine what arguments are appropriate for the current state
  # of the arg parser
  while [ $word_index -ne $COMP_CWORD ]; do
    local this_word="${COMP_WORDS[$word_index]}"

    if [[ $pos_only = 1 || " $this_word " != " -- " ]]; then
      if [[ -n $sub_parsers && " ${sub_parsers[@]} " == *" $this_word "* ]]; then
        # valid subcommand: add it to the prefix & reset the current action
        prefix="${prefix}_$(_shtab_replace_nonword $this_word)"
        _set_parser_defaults
      fi

      if [[ " ${current_option_strings[@]} " == *" $this_word "* ]]; then
        # a new action should be acquired (due to recognised option string or
        # no more input expected from current action);
        # the next positional action can fill in here
        _set_new_action $this_word false
      fi

      if [[ "$current_action_nargs" != "*" ]] && \
         [[ "$current_action_nargs" != "+" ]] && \
         [[ "$current_action_nargs" != "?" ]] && \
         [[ "$current_action_nargs" != *"..." ]] && \
         (( $word_index + 1 - $current_action_args_start_index - $pos_only >= \
            $current_action_nargs )); then
        $current_action_is_positional && let "completed_positional_actions += 1"
        _set_new_action "pos_$completed_positional_actions" true
      fi
    else
      pos_only=1 # "--" delimiter encountered
    fi

    let "word_index+=1"
  done

  # Generate the completions

  COMPREPLY=()
  if [[ $pos_only = 0 && "$completing_word" == -* &&
        ( -z "$current_action_compgen" || "$current_action_is_positional" = true ) ]]; then
    # optional argument started: use option strings
    while IFS= read -r line; do COMPREPLY+=("$line"); done < <(
      compgen -W "${current_option_strings[*]}" -- "$completing_word")
  elif [[ "$previous_word" =~ ^[0-9\&]*[\<\>]\>?$ ]]; then
    # handle redirection operators
    compopt -o filenames 2>/dev/null || : # bash>=4
    while IFS= read -r line; do COMPREPLY+=("$line"); done < <(compgen -f -- "$completing_word")
  else
    # use choices & compgen
    local action_compgen_word="$completing_word"
    # handle tab-completing in the middle of a line (#248 <- #116)
    [[ -n "$current_action_compgen" && "$completing_word" == -* ]] && action_compgen_word=""
    [ -n "$current_action_compgen" ] && {
      [[ "$current_action_compgen" =~ _(file|dir|glob|FILE|DIR|GLOB)|File|Dir|Glob ]] &&
        compopt -o filenames 2>/dev/null || : # bash>=4
      while IFS= read -r line; do COMPREPLY+=("$line"); done < <(
        "$current_action_compgen" "$action_compgen_word")
    }
    while IFS= read -r line; do COMPREPLY+=("$line"); done < <(
      compgen -W "${current_action_choices[*]}" -- "$completing_word")
  fi

  return 0
}

complete -F _shtab_sane sane
